#!/bin/sh
# Check for a currently running instance of the agent
RUNNING_AGENT="`ps ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]'`"
if [ "$RUNNING_AGENT" = "0" ]; then
   # Launch a new instance of the agent
   eval `ssh-agent -s`
   # add host's ssh key for connection to github
   ssh-add $HOME/.host_ssh/id_ed25519
fi
